services:
  frontend:
    image: sakshich01/tdome-front
    ports:
      - "80:80"
  backend:
    image: sakshich01/tdome-front
    environment:
      - PORT=8080
      - CLOUD_NAME=lorem
      - API_KEY=ipsum
      - API_SECRET=loremI
      - SECRET=ipsum
      - DB=mongodb://database:27017/techdome
    ports:
      - "8080:8080"
  database:
    image: mongo:latest
    volumes: 
      - mongo-data:/data/db

volumes:
  mongo-data:
    driver: local
